# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: greencord
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aht20sensor
# "service" is the name of this project. This will also be added to your AWS resource names.
service: API

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  environment:
    AHT20SENSOR_TABLE: aht20sensor-${opt:stage, "dev"}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            # - dynamodb:PutItem
            # - dynamodb:UpdateItem
            # - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.AHT20SENSOR_TABLE}"  

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
  create:
    handler: handler.create
    events: 
      - httpApi:
          path: /sensor
          method: post
  read:
    handler: handler.read
    events:
      - httpApi:
          path: /sensor/{clid}
          method: get
  update:
    handler: handler.update
    events:
      - httpApi:
          path: /sensor/{clid}
          method: patch
  delete:
    handler: handler.delete
    events:
      - httpApi:
          path: /sensor/{clid}
          method: delete

